# Generated by Django 5.0.7 on 2024-11-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivendor_api', '0005_customeraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='adress',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
