# Generated by Django 5.0.7 on 2024-11-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multivendor_api', '0006_remove_customer_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='Customer',
            new_name='customer',
        ),
    ]
